export const JOURNEY_ERROR_CODES = {
  JOURNEY_STAGE_NOT_FOUND: 'JOURNEY_STAGE_NOT_FOUND',
  INVALID_STAGE_ORDER: 'INVALID_STAGE_ORDER',
  JOURNEY_STAGE_IN_USE: 'JOURNEY_STAGE_IN_USE',
  PERSON_ALREADY_IN_STAGE: 'PERSON_ALREADY_IN_STAGE',
} as const;
